# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scan Dockerfile

on:
  push:
    branches:
      - '**'

jobs:
  download-and-scan-dockerfile:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Hello, World
        continue-on-error: true
        run: |
          echo "Is this thing on?" >> $GITHUB_STEP_SUMMARY
      
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          tags: 'tasky:test'
      
      - name: Wizcli Download, Auth, & Scan
        continue-on-error: true
        run: |
          curl -Lo wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli
          ./wizcli auth --id ${{ secrets.CLIENT_ID }} --secret ${{ secrets.CLIENT_SECRET }}
          ./wizcli docker scan --dockerfile Dockerfile --image tasky:test --format json > output.json
          echo "Is this thing on?" >> $GITHUB_STEP_SUMMARY
          export result=$(echo "Scan Result:" $(cat output.json | jq .status.verdict))
          echo $result >> $GITHUB_STEP_SUMMARY
          export link=$(echo "Report Link:" $(cat output.json | jq .reportUrl))
          echo $link >> $GITHUB_STEP_SUMMARY