# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scan Dockerfile

on:
  push:
    branches:
      - '**'

jobs:
  Scan-Dockerfile-with-WizCLI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          tags: 'ubuntu:old'
      
      - name: Wizcli Download
        run: |
          curl -Lo wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli

      - name: Wizcli Auth
        run: |
          ./wizcli auth --id ${{ secrets.CLIENT_ID }} --secret ${{ secrets.CLIENT_SECRET }}

      - name: Wizcli Scan
        id: wizcli-scan
        run: |
          ./wizcli docker scan --dockerfile Dockerfile --image ubuntu:old --format json > output.json   

      - name: Wizcli Scan Failure Summary
        if: ${{ failure() }}
        run: |
          result=$(echo 'Scan Result: :x:' $(cat output.json | jq .status.verdict))
          echo $result >> $GITHUB_STEP_SUMMARY
          link=$(echo 'Report Link:' $(cat output.json | jq .reportUrl))
          echo $link >> $GITHUB_STEP_SUMMARY

      - name: Wizcli Scan Success Summary
        run: |
          result=$(echo 'Scan Result: :white_check_mark:' $(cat output.json | jq .status.verdict))
          echo $result >> $GITHUB_STEP_SUMMARY
          link=$(echo 'Report Link:' $(cat output.json | jq .reportUrl))
          echo $link >> $GITHUB_STEP_SUMMARY
